# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GitTrends' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'lottie-ios', '~> 3.1.2'

  target 'GitTrendsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GitTrendsUITests' do
    # Pods for testing
  end

end
